"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)

import { CheckIcon } from '@radix-ui/react-icons';
import type { SearchResponseFacet } from '@sitecore-search/react';
import { useSearchResultsActions } from '@sitecore-search/react';
import {
  AccordionFacets,
  FacetItem,
  RangeFacet,
  SearchResultsAccordionFacets,
  SearchResultsFacetValueRange,
} from '@sitecore-search/ui';

type PriceFacetProps = {
  min: number;
  max: number;
};

const PriceFacet = ({ min, max }: PriceFacetProps) => {
  return (
    <SearchResultsFacetValueRange
      max={max}
      min={min}
      autoAdjustValues={false}
      className="relative flex items-center select-none touch-none w-full h-5 mb-8"
    >
      <RangeFacet.Track className="relative grow h-[3px] rounded-full bg-gray-300 dark:bg-gray-600">
        <RangeFacet.Range className="absolute h-full bg-[#005EB8] rounded-full" />
      </RangeFacet.Track>
      <RangeFacet.Start className="block w-5 h-5 bg-white shadow-[0_2px_6px_rgba(0,0,0,0.15)] text-[10px] leading-5 text-center cursor-pointer rounded-[10px] hover:bg-[#005EB8] hover:border-2 hover:border-[#C8102E] focus:shadow-[0_0_0_3px_#005EB8] transition-all border-2 border-gray-300">
        {(value) => <span className="absolute text-sm left-0 top-[30px] text-gray-900 dark:text-white">${value}</span>}
      </RangeFacet.Start>
      <RangeFacet.End className="block w-5 h-5 bg-white shadow-[0_2px_6px_rgba(0,0,0,0.15)] text-[10px] leading-5 text-center cursor-pointer rounded-[10px] hover:bg-[#005EB8] hover:border-2 hover:border-[#C8102E] focus:shadow-[0_0_0_3px_#005EB8] transition-all border-2 border-gray-300">
        {(value) => <span className="absolute text-sm left-0 top-[30px] text-gray-900 dark:text-white">${value}</span>}
      </RangeFacet.End>
    </SearchResultsFacetValueRange>
  );
};

type SearchFacetsProps = {
  facets: SearchResponseFacet[];
};

const SearchFacets = ({ facets }: SearchFacetsProps) => {
  const { onFacetClick } = useSearchResultsActions();
  return (
    <SearchResultsAccordionFacets
      defaultFacetTypesExpandedList={["type"]}
      onFacetTypesExpandedListChange={() => {}}
      onFacetValueClick={onFacetClick}
      className="w-full"
    >
      {facets.map((f) => (
        <AccordionFacets.Facet
          facetId={f.name}
          key={f.name}
          className="block border-b border-gray-200 dark:border-gray-600 mb-4 pb-4 last:border-b-0 last:mb-0 last:pb-0"
        >
          <AccordionFacets.Header className="flex">
            <AccordionFacets.Trigger className="text-base font-bold text-gray-900 dark:text-white hover:text-[#005EB8] dark:hover:text-blue-400 focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 rounded transition-colors w-full text-left flex justify-between items-center py-2">
              <span>{f.label}</span>
              <span className="text-[#005EB8] dark:text-blue-400 text-sm">+</span>
            </AccordionFacets.Trigger>
          </AccordionFacets.Header>
          <AccordionFacets.Content className="mt-3">
            {f.name !== 'price' ? (
              <AccordionFacets.ValueList className="list-none flex flex-col space-y-2">
                {f.value.map((v, index: number) => (
                  <FacetItem
                  key={v.id}
                    {...{
                      index,
                      facetValueId: v.id,
                    }}
                    className="group flex items-center text-sm cursor-pointer py-1"
                  >
                    <AccordionFacets.ItemCheckbox className="form-checkbox flex-none w-4 h-4 border-2 border-gray-400 dark:border-gray-500 rounded cursor-pointer transition duration-200 ease-in-out hover:border-[#005EB8] focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 aria-checked:bg-[#005EB8] aria-checked:border-[#005EB8] aria-checked:hover:bg-[#C8102E] aria-checked:hover:border-[#C8102E]">
                      <AccordionFacets.ItemCheckboxIndicator className="text-white w-4 h-4">
                        <CheckIcon className="w-3 h-3" />
                      </AccordionFacets.ItemCheckboxIndicator>
                    </AccordionFacets.ItemCheckbox>
                    <AccordionFacets.ItemLabel className="text-sm ms-3 text-gray-700 dark:text-gray-300 group-hover:text-[#005EB8] dark:group-hover:text-blue-400 transition-colors">
                      {v.text} {v.count && <span className="text-gray-500 dark:text-gray-400 ml-1">({v.count})</span>}
                    </AccordionFacets.ItemLabel>
                  </FacetItem>
                ))}
              </AccordionFacets.ValueList>
            ) : (
              <PriceFacet min={Math.floor(f.value[0].min)} max={Math.floor(f.value[f.value.length - 1].max)} />
            )}
          </AccordionFacets.Content>
        </AccordionFacets.Facet>
      ))}
    </SearchResultsAccordionFacets>
  );
};

export default SearchFacets;
