"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)
import { useRouter } from 'next/navigation'

import type { ActionProp, ItemClickedAction } from '@sitecore-search/react';
import { ArticleCard } from '@sitecore-search/ui';
import Image from 'next/image'
import { DEFAULT_IMG_URL } from '@/app/_data/customizations';

type ArticleCardItemCardProps = {
  className?: string;
  displayText?: boolean;
  article: any;
  onItemClick: ActionProp<ItemClickedAction>;
  index: number;
};

const ArticleHorizontalItemCard = ({ className = '', article, onItemClick, index }: ArticleCardItemCardProps) => {
  const router = useRouter();
  const validImageUrl = article.image_url?.trim() ? article.image_url : DEFAULT_IMG_URL;

  return (
    <ArticleCard.Root
      key={article.id}
      className={`group flex flex-row p-5 my-4 flex-nowrap max-h-52 w-full relative border-2 border-gray-200 dark:border-gray-600 rounded-lg hover:shadow-lg hover:border-[#C8102E] hover:transition-all hover:ease-linear hover:duration-300 focus-within:border-[#005EB8] focus-within:transition-all focus-within:ease-linear focus-within:duration-300 focus-within:hover:shadow-lg bg-white dark:bg-gray-800 ${className}`}
    >
      <div className="w-[25%] flex-none overflow-hidden bg-gray-100 dark:bg-gray-700 rounded-l-lg">
        <Image
          src={validImageUrl}
          className="h-full w-full object-cover object-center lg:h-full lg:w-full"
          alt='alt'
          width={500}
          height={115}
        />
      </div>
      <div className="pl-5 grow flex-col">
        <a
          className="focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 rounded"
          href={article.url}
          onClick={(event) => {
            event.preventDefault();
            onItemClick({
              id: article.id,
              index,
              sourceId: article.source_id,
            });
            router.push(`/detail/${article.id}`);
          }}
        >
          <span aria-hidden="true" className="absolute inset-0"></span>
          <ArticleCard.Title className="text-base text-gray-900 dark:text-white group-hover:text-[#C8102E] transition-colors">{article.name || article.title}</ArticleCard.Title>
        </a>
        <ArticleCard.Subtitle className="mt-3 text-sm text-gray-600 dark:text-gray-300 h-[100px] overflow-hidden">
          {article.subtitle}
        </ArticleCard.Subtitle>
      </div>
    </ArticleCard.Root>
  );
};
export default ArticleHorizontalItemCard;
