// This component was generated by @sitecore-search/cli on Mon Aug 26 2024 13:33:05 GMT+0200 (Central European Summer Time)
import type { ChangeEvent, SyntheticEvent } from 'react';
import { useCallback } from 'react';

import Spinner from '@/app/_widgets/components/Spinner';
import SuggestionBlock from '@/app/_widgets/components/SuggestionBlock';
import type { PreviewSearchInitialState } from '@sitecore-search/react';
import { WidgetDataType, usePreviewSearch, widget } from '@sitecore-search/react';
import { ArticleCard, PreviewSearch } from '@sitecore-search/ui';
import React from 'react';
import Image from 'next/image'
import { useRouter } from 'next/navigation'
import { MagnifyingGlassIcon } from '@radix-ui/react-icons'


const SEARCH_CONFIG = {
  source: process.env.NEXT_PUBLIC_SEARCH_SOURCE as string,
};

type ArticleModel = {
  id: string;
  title: string;
  image_url: string;
  url: string;
  source_id?: string;
  name: string;
};

type InitialState = PreviewSearchInitialState<'itemsPerPage' | 'suggestionsList'>;

export const PreviewSearchComponent = ({ defaultItemsPerPage = 6 }) => {
  const router = useRouter();
  const {
    actions: { onItemClick, onKeyphraseChange },
    queryResult,
    queryResult: {
      isFetching,
      isLoading,
      data: { suggestion: { title_context_aware: articleSuggestions = [] } = {} } = {},
    },
  } = usePreviewSearch<ArticleModel, InitialState>({
    state: {
      suggestionsList: [{ suggestion: 'title_context_aware', max: 6 }],
      itemsPerPage: defaultItemsPerPage,
    },
    query: (query) => {
      if (SEARCH_CONFIG.source !== '') {
        const sources = SEARCH_CONFIG.source.split('|');
        sources.forEach(source => {
            query.getRequest().addSource(source.trim());
        });
      }
    },
  });

  const loading = isLoading || isFetching;
  const keyphraseHandler = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => {
      const target = event.target;
      onKeyphraseChange({ keyphrase: target.value });
    },
    [onKeyphraseChange],
  );
  const handleSubmit = (e: SyntheticEvent): void => {
    e.preventDefault();
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    const target = e.target.query as HTMLInputElement;
    const searchValue = target.value.trim();
    // If empty, navigate to search page without query to show all results
    if (searchValue === '') {
      router.push('/search');
    } else {
      router.push(`/search?q=${encodeURIComponent(searchValue)}`);
    }
    target.value = '';
  };

  const handleSearchClick = (): void => {
    const input = document.querySelector('input[name="query"]') as HTMLInputElement;
    if (input) {
      const searchValue = input.value.trim();
      if (searchValue === '') {
        router.push('/search');
      } else {
        router.push(`/search?q=${encodeURIComponent(searchValue)}`);
      }
      input.value = '';
    }
  };

  return (
    <PreviewSearch.Root>
      <form onSubmit={handleSubmit} className="relative flex items-center">
        <PreviewSearch.Input
          name="query"
          className="w-full rounded-md box-border py-2.5 pl-4 pr-12 focus:outline-solid focus:outline-2 focus:outline-[#005EB8] dark:focus:outline-[#005EB8] border-2 border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 dark:text-gray-100 text-gray-900 placeholder:text-gray-500 transition-all"
          onChange={keyphraseHandler}
          autoComplete="off"
          placeholder="Search products, services, and more..."
        />
        <button
          type="submit"
          onClick={handleSearchClick}
          className="absolute right-2 p-2 text-[#005EB8] dark:text-blue-400 hover:text-[#C8102E] dark:hover:text-red-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md transition-colors focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2"
          aria-label="Search"
        >
          <MagnifyingGlassIcon className="w-5 h-5" />
        </button>
      </form>
      <PreviewSearch.Content
        className="flex justify-center pt-0 h-[400px] shadow-[0_4px_6px_rgba(0,0,0,0.1)] transition-opacity	w-[var(--radix-popover-trigger-width)] bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-md mt-1"
      >
        <Spinner loading={loading} />

        {!loading  &&
          <React.Fragment key="1">
            {articleSuggestions.length > 0 && (
              <PreviewSearch.Suggestions className="block box-border list-none w-[16rem] text-sm">
                <SuggestionBlock blockId={'title_context_aware'} items={articleSuggestions} title={'Suggestions'} />
              </PreviewSearch.Suggestions>
            )}
            <PreviewSearch.Results defaultQueryResult={queryResult}>
              {({ isFetching: loading, data: { content: articles = [] } = {} }) => (
                <PreviewSearch.Items
                  data-loading={loading}
                  className="flex flex-[3] bg-white dark:bg-gray-700 overflow-y-auto data-[loading=false]:grid data-[loading=false]:list-none data-[loading=false]:m-0 data-[loading=false]:p-2 data-[loading=false]:gap-3 data-[loading=false]:grid-cols-3"
                >
                  <Spinner loading={loading} />
                  {!loading &&
                    articles.map((article, index) => (
                      
                      <PreviewSearch.Item key={article.id} asChild>
                        <PreviewSearch.ItemLink
                          href={article.url}
                          onClick={() => {
                            onItemClick({ id: article.id, index, sourceId: article.source_id });
                            router.push('/detail/' + article.id);
                          }}
                          className="flex box-border no-underline w-full text-gray-900 dark:text-white focus:shadow-md"
                        >
                          <ArticleCard.Root className="w-full shadow-sm rounded-md p-3 cursor-pointer block border border-gray-200 dark:border-gray-600 text-center focus-within:shadow-md focus-within:border-[#005EB8] hover:shadow-md hover:border-[#C8102E] transition-all dark:text-white">
                            <div className="m-auto mb-[10px] relative h-[6em] flex justify-center items-center overflow-hidden">
                              <Image
                                src={article.image_url}
                                className="block w-auto max-w-full h-auto max-h-full"
                                alt='alt'
                                width={200}
                                height={100}
                              />
                            </div>
                            <ArticleCard.Title className="max-h-[2rem] overflow-hidden m-0 mb-2 text-xs">
                              {article.name}
                            </ArticleCard.Title>
                          </ArticleCard.Root>
                        </PreviewSearch.ItemLink>
                      </PreviewSearch.Item>
                    ))}
                </PreviewSearch.Items>
              )}
            </PreviewSearch.Results>
          </React.Fragment>
        }
      </PreviewSearch.Content>
    </PreviewSearch.Root>
  );
};
const PreviewSearchWidget = widget(PreviewSearchComponent, WidgetDataType.PREVIEW_SEARCH, 'content');
export default PreviewSearchWidget;
