"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 12:45:56 GMT+0200 (Central European Summer Time)
import { Accordion, Content, Header, Item, Trigger } from '@radix-ui/react-accordion';
import { ChevronDownIcon } from '@radix-ui/react-icons';
import { WidgetDataType, useQuestions, widget } from '@sitecore-search/react';

const SEARCH_CONFIG = {
  source: process.env.NEXT_PUBLIC_SEARCH_SOURCE as string,
};

type Question = {
  question: string;
  answer: string;
};

const MainQuestionComponent = ({ answer, question }: Question) => {
  return (
    <div className="p-4 dark:text-gray-100">
      <h4 className="text-lg font-bold text-gray-900 dark:text-white">{question}</h4>
      <p className="mt-3 text-gray-700 dark:text-gray-300 leading-relaxed">{answer}</p>
    </div>
  );
};

type RelatedQuestionsProps = {
  relatedQuestions: Array<Question>;
};

const RelatedQuestionsComponent = ({ relatedQuestions = [] }: RelatedQuestionsProps) => {
  return (
    <div className="dark:text-gray-100">
      {relatedQuestions.length > 0 && (
        <Accordion className="w-full mt-4 px-2" type="multiple">
          <h4 className="text-md font-bold mb-4 text-gray-900 dark:text-white">People also ask ...</h4>
          {relatedQuestions.map(({ answer, question }, index) => (
            <Item className="w-full cursor-pointer border-b border-gray-200 dark:border-b-gray-600 py-4 hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors" value={`${answer}-${index}`} key={index}>
              <Header>
                <Trigger className="w-full flex justify-between gap-x-2 text-left text-sm text-gray-900 dark:text-white hover:text-[#005EB8] dark:hover:text-blue-400 focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 rounded transition-colors">
                  <span>{question}</span>
                  <ChevronDownIcon height={20} width={20} className="text-[#005EB8] dark:text-blue-400 flex-shrink-0" />
                </Trigger>
              </Header>
              <Content className="pt-5 font-light text-sm text-gray-700 dark:text-gray-300 leading-relaxed">{answer}</Content>
            </Item>
          ))}
        </Accordion>
      )}
    </div>
  );
};

export const QuestionsAnswersComponent = ({ defaultKeyphrase = '', defaultRelatedQuestions = 5 }) => {
  const {
    queryResult: {
      data: {
        related_questions: relatedQuestionsResponse = [],
        answer: { answer, question } = {
          answer: undefined,
          question: undefined,
        },
      } = {},
    },
  } = useQuestions({
    state: {
      keyphrase: defaultKeyphrase,
      relatedQuestions: defaultRelatedQuestions,
    },
    query: (query) => {
      if (SEARCH_CONFIG.source !== '') {
        const sources = SEARCH_CONFIG.source.split('|');
        sources.forEach(source => {
            query.getRequest().addSource(source.trim());
        });
      }
    }
  });
  return (
    <div>
      {((answer && question) || relatedQuestionsResponse.length > 0) && (
        <div className="rounded-lg border-2 border-gray-200 dark:border-gray-600 p-4 my-6 shadow-md bg-white dark:bg-gray-800">
          {answer && question && <MainQuestionComponent answer={answer} question={question} />}
          {relatedQuestionsResponse.length > 0 && (
            <RelatedQuestionsComponent relatedQuestions={relatedQuestionsResponse} />
          )}
        </div>
      )}
    </div>
  );
};

const QuestionsAnswersWidget = widget(QuestionsAnswersComponent, WidgetDataType.QUESTIONS, 'website_content');

export default QuestionsAnswersWidget;
