"use client"
// This component was generated by @sitecore-search/cli on Mon Aug 26 2024 13:33:05 GMT+0200 (Central European Summer Time)
import { useRouter } from 'next/navigation'; 

import { usePreviewSearchActions } from '@sitecore-search/react';
import { PreviewSearch } from '@sitecore-search/ui';

type SuggestionBlockProps = {
  items: Array<{ text: string }>;
  title: string;
  blockId: string;
  filterAttribute?: string;
  disabled?: boolean;
};

const SuggestionBlock = ({ items, title, blockId, filterAttribute, disabled }: SuggestionBlockProps) => {
  const { onSuggestionClick } = usePreviewSearchActions();
  const router = useRouter();
  return (
    <>
      {items.length > 0 && (
        <PreviewSearch.SuggestionsGroup className="flex flex-1 flex-col" id={blockId} filterAttribute={filterAttribute}>
          <h2 className="box-border pl-1 block text-lg font-bold m-2 text-gray-900 dark:text-gray-100">{title}</h2>
          {items.map(({ text }) => (
            <PreviewSearch.SuggestionTrigger
              className="cursor-pointer p-2.5 text-sm rounded-md mx-1 data-[state=active]:outline-none data-[state=active]:text-[#005EB8] dark:data-[state=active]:text-blue-400 data-[state=active]:bg-blue-50 dark:data-[state=active]:bg-blue-900/20 focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 focus:bg-blue-50 dark:focus:bg-blue-900/20 hover:bg-blue-50 dark:hover:bg-blue-900/20 hover:text-[#005EB8] dark:hover:text-blue-400 text-gray-700 dark:text-gray-300 transition-colors"
              id={text}
              key={text}
              asChild
              disabled={disabled}
            >
              <a
                onClick={() => {
                  onSuggestionClick({
                    name: blockId,
                    title,
                    value: text,
                    displayName: text,
                  });
                  router.push('/search?q=' + text);
                }}
              >
                {text}
              </a>
            </PreviewSearch.SuggestionTrigger>
          ))}
        </PreviewSearch.SuggestionsGroup>
      )}
    </>
  );
};

export default SuggestionBlock;
