"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)

import { useSearchResultsActions, useSearchResultsSelectedFilters } from '@sitecore-search/react';

const buildRangeLabel = (min: number | undefined, max: number | undefined): string => {
  return typeof min === 'undefined' ? `< $${max}` : typeof max === 'undefined' ? ` > $${min}` : `$${min} - $${max}`;
};
const buildFacetLabel = (selectedFacet: { min?: number; max?: number; valueLabel?: string }) => {
  if ('min' in selectedFacet || 'max' in selectedFacet) {
    return `${buildRangeLabel(selectedFacet.min, selectedFacet.max)}`;
  }
  return `${selectedFacet.valueLabel}`;
};

const Filter = () => {
  const selectedFacetsFromApi = useSearchResultsSelectedFilters();
  const { onRemoveFilter, onClearFilters } = useSearchResultsActions();
  return selectedFacetsFromApi.length > 0 ? (
    <div className="mb-6 pb-6 border-b border-gray-200 dark:border-gray-600">
      <div className="flex flex-row justify-between items-center mb-4">
        <h3 className="text-base font-bold text-gray-900 dark:text-white">Active Filters</h3>
        <button
          onClick={onClearFilters}
          className="text-sm font-semibold text-[#005EB8] dark:text-blue-400 hover:text-[#C8102E] dark:hover:text-red-400 focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 rounded transition-colors underline"
        >
          Clear All
        </button>
      </div>
      <div className="flex flex-wrap gap-2">
        {selectedFacetsFromApi.map((selectedFacet) => (
          <button
            key={`${selectedFacet.facetId}${selectedFacet.facetLabel}${selectedFacet.valueLabel}`}
            onClick={() => onRemoveFilter(selectedFacet)}
            className="text-sm font-medium text-white bg-[#005EB8] hover:bg-[#C8102E] rounded px-3 py-1.5 whitespace-nowrap relative pr-8 cursor-pointer transition-all duration-200 focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 before:content-['×'] before:absolute before:right-2 before:top-1/2 before:-translate-y-1/2 before:text-white before:text-lg before:leading-none before:font-bold"
          >
            {buildFacetLabel(selectedFacet)}
          </button>
        ))}
      </div>
    </div>
  ) : (
    <></>
  );
};

export default Filter;
