"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)

type QueryResultsSummaryProps = {
    currentPage: number;
    itemsPerPage: number;
    totalItemsReturned: number;
    totalItems: number;
  };
  const QueryResultsSummary = ({
    currentPage,
    itemsPerPage,
    totalItems,
    totalItemsReturned,
  }: QueryResultsSummaryProps) => {
    return (
      <div className="text-sm text-gray-700 dark:text-gray-300">
        Showing <span className="font-semibold text-gray-900 dark:text-white">{itemsPerPage * (currentPage - 1) + 1}</span> - <span className="font-semibold text-gray-900 dark:text-white">{itemsPerPage * (currentPage - 1) + totalItemsReturned}</span> of{' '}
        <span className="font-semibold text-[#005EB8] dark:text-blue-400">{totalItems.toLocaleString()}</span> results
      </div>
    );
  };
  
  export default QueryResultsSummary;
  