"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)
import { useSearchResultsActions } from '@sitecore-search/react';
import { Select, SortSelect } from '@sitecore-search/ui';

type ResultsPerPageProps = {
  defaultItemsPerPage: number;
};

const ResultsPerPage = ({ defaultItemsPerPage }: ResultsPerPageProps) => {
  const { onResultsPerPageChange } = useSearchResultsActions();
  return (
    <div className="flex items-center gap-2">
      <label className="text-sm text-gray-700 dark:text-gray-300 font-medium">Show:</label>
      <Select.Root
        defaultValue={String(defaultItemsPerPage)}
        onValueChange={(v) =>
          onResultsPerPageChange({
            numItems: Number(v),
          })
        }
      >
        <Select.Trigger className="cursor-pointer inline-flex items-center bg-white dark:bg-gray-800 h-10 gap-2 py-2 px-4 border border-gray-300 dark:border-gray-600 rounded text-gray-900 dark:text-white hover:border-[#005EB8] dark:hover:border-blue-400 hover:bg-gray-50 dark:hover:bg-gray-700 focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 transition-all shadow-sm">
          <Select.SelectValue className="text-sm font-semibold text-[#005EB8] dark:text-blue-400" />
          <Select.Icon className="text-gray-500" />
        </Select.Trigger>
        <Select.SelectContent className="bg-white dark:bg-gray-800 shadow-lg border border-gray-200 dark:border-gray-700 z-[100] min-w-[100px] rounded">
          <Select.Viewport className="p-1">
            <Select.SelectItem
              value="10"
              className="flex rounded items-center leading-none cursor-pointer select-none whitespace-no-wrap h-9 px-3 hover:bg-[#005EB8] hover:text-white data-[state=checked]:text-[#005EB8] data-[state=checked]:bg-blue-50 dark:data-[state=checked]:bg-blue-900/20 data-[state=checked]:font-semibold focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 transition-colors text-sm"
            >
              <SortSelect.OptionText>10</SortSelect.OptionText>
            </Select.SelectItem>

            <Select.SelectItem
              value="25"
              className="flex rounded items-center leading-none cursor-pointer select-none whitespace-no-wrap h-9 px-3 hover:bg-[#005EB8] hover:text-white data-[state=checked]:text-[#005EB8] data-[state=checked]:bg-blue-50 dark:data-[state=checked]:bg-blue-900/20 data-[state=checked]:font-semibold focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 transition-colors text-sm"
            >
              <SortSelect.OptionText>25</SortSelect.OptionText>
            </Select.SelectItem>

            <Select.SelectItem
              value="50"
              className="flex rounded items-center leading-none cursor-pointer select-none whitespace-no-wrap h-9 px-3 hover:bg-[#005EB8] hover:text-white data-[state=checked]:text-[#005EB8] data-[state=checked]:bg-blue-50 dark:data-[state=checked]:bg-blue-900/20 data-[state=checked]:font-semibold focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 transition-colors text-sm"
            >
              <SortSelect.OptionText>50</SortSelect.OptionText>
            </Select.SelectItem>
          </Select.Viewport>
        </Select.SelectContent>
      </Select.Root>
    </div>
  );
};

export default ResultsPerPage;
