"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)
import React from 'react';

import { CardViewSwitcher } from '@sitecore-search/ui';

type CardViewSwitcherProps = {
  onToggle: (value: string) => void;
  defaultCardView: 'list' | 'grid';
  GridIcon: React.ComponentType<{ className?: string }>;
  ListIcon: React.ComponentType<{ className?: string }>;
};

const CardViewSwitcherComponent = ({ onToggle, defaultCardView, GridIcon, ListIcon }: CardViewSwitcherProps) => {
  return (
    <CardViewSwitcher.Root onValueChange={onToggle} defaultValue={defaultCardView} className="inline-flex border border-gray-300 dark:border-gray-600 rounded p-0.5 bg-gray-100 dark:bg-gray-700">
      <CardViewSwitcher.Item
        value="grid"
        aria-label="Grid View"
        className="items-center rounded bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-400 flex h-9 justify-center w-9 hover:bg-gray-200 dark:hover:bg-gray-600 hover:text-[#005EB8] dark:hover:text-blue-400 data-[state=on]:bg-[#005EB8] data-[state=on]:text-white dark:data-[state=on]:bg-[#005EB8] dark:data-[state=on]:text-white focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 transition-all"
      >
        <GridIcon className="w-4 h-4" />
      </CardViewSwitcher.Item>
      <CardViewSwitcher.Item
        value="list"
        aria-label="List View"
        className="items-center rounded bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-400 flex h-9 justify-center w-9 hover:bg-gray-200 dark:hover:bg-gray-600 hover:text-[#005EB8] dark:hover:text-blue-400 data-[state=on]:bg-[#005EB8] data-[state=on]:text-white dark:data-[state=on]:bg-[#005EB8] dark:data-[state=on]:text-white focus:outline-[#005EB8] focus:outline-2 focus:outline-offset-2 transition-all"
      >
        <ListIcon className="w-4 h-4" />
      </CardViewSwitcher.Item>
    </CardViewSwitcher.Root>
  );
};

export default CardViewSwitcherComponent;
